# Generated by Django 4.2.30 on 2026-08-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('puede_ver_tablero', 'Puede ver el tablero de comandas y categorias'), ('puede_crear_comandas', 'Puede iniciar el flujo de crear una comanda')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
